// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function UploadImage(arg1) {
  return window['go']['main']['App']['UploadImage'](arg1);
}

export function ValidateImageFile(arg1) {
  return window['go']['main']['App']['ValidateImageFile'](arg1);
}

export function VerifyTwoFactor(arg1) {
  return window['go']['main']['App']['VerifyTwoFactor'](arg1);
}
