// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCurrentUser():Promise<main.LoginResponse>;

export function IsAuthenticated():Promise<boolean>;

export function Login(arg1:main.LoginRequest):Promise<main.LoginResponse>;

export function Logout():Promise<main.LoginResponse>;

export function OpenFileDialog():Promise<string>;

export function UploadImage(arg1:main.UploadRequest):Promise<main.UploadResponse>;

export function ValidateImageFile(arg1:string):Promise<Record<string, any>>;

export function VerifyTwoFactor(arg1:main.TwoFactorRequest):Promise<main.LoginResponse>;
